config/routes.rb
Rails.application.routes.draw do
  root "home#home"
  # root "dashboards#show"
  get 'google_api/auth', to: "sessions#create"
  # get 'o/oauth2/auth', to: "sessions#create"
  get 'login', to: "sessions#new"
  delete 'logout', to: "sessions#destroy"

  get 'dashboard/plot', to: "dashboards#index"
  resource :dashboard, only: [:show]

  resources :journal_entries, only: [:new, :show, :index, :create]

  namespace :api do
    namespace :v1 do
      resources :journal_entries, only: [:create]
      resource :alert_analytics, only: [:show]
      resources :emotions, only: [:create, :destroy]
    end
  end
end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  belongs_to :user
  has_many :emotions

  def datetime
    "#{created_at.month}/#{created_at.day}/#{created_at.year} #{created_at.hour}h"
  end

  def self.net_data
    Emotion.where(journal_entry: self.all).scores_to_hash.merge({"total" => count})
  end

  def prior_week_entries
    JournalEntry.where("created_at >= :start_date AND created_at <= :end_date",
    {start_date: created_at-7.day, end_date: created_at, user_id: user_id})
  end

  def self.closest_entry_to(time)
    all.sort_by{|je| (je.created_at - time)**2}.first
  end

  def self.scores_for(emotion_prototype, start_time, end_time)
    entries = where("created_at >= :start_time AND created_at <= :end_time",  {start_time: start_time, end_time: end_time}).all
    emps = Emotion.order(created_at: :desc)
                  .includes(:journal_entry)
                  .includes(:emotion_prototype)
                  .where(emotion_prototype: emotion_prototype, journal_entry: entries)
                  .map do |emp|
                    {
                      created_at: emp.journal_entry.created_at,
                      score: emp.score,
                      tag: emp.journal_entry.tag
                    }
                  end
  end
end

app/controllers/api/v1/journal_entries_controller.rb
class Api::V1::JournalEntriesController < ApplicationController
  def create
    user_id = current_user.id
    if journal_params["user_id"].to_i == user_id
      save = SaveToDriveService.new(google_service, user_id)
      reply = save.post_file_to_drive(params[:tag], params[:body])
      @entry = JournalEntry.create(tag: params[:tag],
                              file_id: reply.id,
                              user_id: user_id)
      process_emotion_params
      render json: {created: "success"}
    else
      render json: {created: "error"}
    end
  end

private

  def journal_params
    params.permit!
    params.except("tag","body","controller","action")
  end

  def process_emotion_params
    journal_params.except("user_id").each do |emotion, score|
      proto = current_user.emotion_prototypes.find_by(name: emotion)
      @entry.emotions.create(emotion_prototype: proto, score: score)
    end
  end
end

app/controllers/journal_entries_controller.rb
require 'google/apis/drive_v2'
require 'google/api_client/client_secrets'

class JournalEntriesController < ApplicationController
  def index
    @entries = current_user.journal_entries
    render layout: 'wide',  :locals => {:background => "dashboard3"}
  end

  def new
    @entry = JournalEntry.new(user: current_user)
    render layout: 'wide',  :locals => {:background => "dashboard3"}
  end

  def show
    file_name = file_name(params[:id])
    file_contents = file_from_drive(file_name)
    @journal_entry = {entry: @entry, body: file_contents, :empty? => file_contents.empty?}
    render layout: 'wide',  :locals => {:background => "dashboard3"}
  end

private

  def file_name(id)
    @entry = JournalEntry.find(id)
    file_name = "#{current_user.id}:#{@entry.file_id}.txt"
  end

  def file_from_drive(file_name)
    buffer = StringIO.new
    google_service.drive.get_file(@entry.file_id, download_dest: buffer)
    buffer.rewind
    buffer.read
  end
end

app/views/journal_entries/index.html.erb
<br>
  <h3 id="header" style="text-align:center">Past Journal Entries</h3>
<br>

<div class="container browse-journal">
    <table class="table journal-index table-bordered table-hover table-responsive">
      <col width="20">
      <col width="250">
      <thead>
        <tr>
          <th>Created At</th>
          <th>Entry Tag</th>
        </tr>
      </thead>
      <div class="tbody">
        <tbody>
          <% @entries.reverse.each do |entry| %>
          <tr>
            <td> <%= link_to entry.datetime, journal_entry_path(entry) %></td>
            <td> <%= link_to entry.tag,  journal_entry_path(entry) %></td>
          </tr>
          <% end %>
        </tbody>
      </div>
    </table>
</div>

app/views/journal_entries/new.html.erb
<br>
  <h3 id="header" style="text-align:center">New Journal Entry</h3>
<br>

<div class="container entry-form active">
  <div class="row">
    <div class="col-md-2 emotion-select">
      <div class="row">
        <div class="col-md-1">
          <br>
        </div>
        <br>
        <div class="col-md-10 emotions">
          <%= render(partial: 'new_entry/sliders') %>
        </div>
      </div>
    </div>
    <%= render(partial: 'new_entry/input_form') %>
  </div>
</div>

app/views/journal_entries/show.html.erb
<br>
  <h3 id="header" style="text-align:center"><%=@journal_entry[:entry].datetime%></h3>
<br>

<div class="container entry-form inactive">
  <div class="row">
    <div class="col-md-2 emotion-select">
      <div class="row">
        <div class="col-md-1">
          <br>
        </div>
        <br>
        <div class="col-md-10 emotions">
          <div class="emotion-container">

            <% @journal_entry[:entry].emotions.each do |emotion| %>
              <% name = emotion.name %>
              <% color = emotion.color %>
              <% description = emotion.description %>
              <div class="emotion-text", id="<%= emotion.name %>">
                <p>
                  <a href="#", class="description"><span><strong><%= "#{name.capitalize}: "%></strong><%=" #{description}" %></span>?</a><span style="padding-left: 1em"></span><%= name.capitalize %><br>
                </p>
                <input style="background-color:<%= color %>" class="slider <%=name%>-slide" type="range" name="<%=name%>" min="0" max="10" value="<%= emotion.score %>" readonly="readonly"><br>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
    <div class="col-md-10">
      <%= form_for(@journal_entry[:entry], html:{autocomplete:"off"}) do |f| %>
      <div class="form-group">
          <%= f.text_field :tag, id: "tag", readonly: "readonly", value: @journal_entry[:entry].tag %>
        <% if @journal_entry[:empty?] %>
          <%= f.text_area :body, value: "Sorry, it appears this journal entry has been deleted from your Google Drive account.", readonly: "readonly" %>
        <% else %>
          <%= f.text_area :body, value: @journal_entry[:body], readonly: "readonly" %>
        <% end %>
      </div>
      <% end %>
      <div class="user" name="<%= @journal_entry[:entry].user.id %>">
      </div>
    </div>
  </div>
</div>