config/routes.rb
Rails.application.routes.draw do
  root "home#home"
  # root "dashboards#show"
  get 'google_api/auth', to: "sessions#create"
  # get 'o/oauth2/auth', to: "sessions#create"
  get 'login', to: "sessions#new"
  delete 'logout', to: "sessions#destroy"

  get 'dashboard/plot', to: "dashboards#index"
  resource :dashboard, only: [:show]

  resources :journal_entries, only: [:new, :show, :index, :create]

  namespace :api do
    namespace :v1 do
      resources :journal_entries, only: [:create]
      resource :alert_analytics, only: [:show]
      resources :emotions, only: [:create, :destroy]
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    render layout: 'wide',  :locals => {:background => "dashboard3"}
  end

  def index
    @chart = overall_chart_service.render_overall_chart
    @chart2, @chart3 = comparison_chart_service.render_current_and_similar_charts
    if comparison_charts_fail?
      flash.now[:comparison_error] = comparison_chart_service.graph_fail_reasons
    end
    render layout: 'wide',  :locals => {:background => "dashboard3"}
  end

private

  def overall_chart_service
    @ocs ||= OverallChartService.new(current_user, dates_for_overall_chart)
  end

  def comparison_chart_service
    @ccs ||= ComparisonChartService.new(current_user, cps.interval_params, cps.emotion_params)
  end

  def cps
    @cps ||= ChartParamsService.new(current_user, params)
  end

  def comparison_charts_fail?
    !comparison_chart_service.render_comparison_graph? && params[:emotions]
  end

  def dates_for_overall_chart
    cps.datetime_params
  end
end

app/views/dashboards/index.html.erb
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
$(function() {
  $( "#datepicker1" ).datepicker();
  $( "#datepicker2" ).datepicker();
});
</script>

<div class="" style="min-height: 2em">
</div>
<div class="container datepicks">
  <div class="">
    <br>
  </div>
  <form action="plot" style="text-align: center">
    <h4>Scope your journal entries: What time range would you like to see?</h4>
    <span>
      <input type="text" class="datepicker" id="datepicker1" name="start_date" placeholder="Start Date">
    </span>
    <span>&nbsp;</span>
    <span>
      <input type="text" class="datepicker" id="datepicker2" name="end_date" placeholder="End Date">
    </span>
    <span>|||  <input type="submit" value="Send" class="datepickerbutton"></span>
  </form>
  <div class="">
    <br>
  </div>
</div>
<div class="" style="min-height: 2em">
</div>

<div class="container form-entry">
  <%= high_chart("some_id", @chart) %>
</div>

<div class="" style="min-height: 2em">
</div>

<div class="container">
  <div class="container datepicks">
    <div class="">
      <br>
    </div>
    <%= form_for :emotions, url: "/dashboard/plot", method: :get do |f|  %>
      <h4 style="text-align: center">
        Search for similar journal entries:  How many days back and which emotions would you like to compare?
      </h4>
      <div style="text-align: center">
        <% current_user.active_emotion_prototypes.each do |emp| %>
          <%= f.label "#{emp.name.capitalize}" %>:
          <%= f.check_box "#{emp.name}" %> &nbsp;&nbsp;
        <% end %>
        <br>
        <%= f.number_field "days", class: "datepicker", placeholder:"Days back" %> |||
        <%= f.submit "Send", class: "datepicker" %>
      </div>
      <br>
    <% end %>
    <div class="">
      <br>
    </div>
  </div>
  <div class="row">
    <br>
  </div>
  <div class="row">
    <div class="" style="color:white; text-align:center; font-size:large">
      <%= flash[:comparison_error] %>
    </div>
    <div class="col-md-6">
      <%= high_chart("some_other_id", @chart2) if @chart2 %>
    </div>
    <div class="col-md-6">
      <%= high_chart("somethird", @chart3) if @chart3 %>
    </div>
  </div>
</div>

<div class="">
  <br><br><br>
</div>

<br>

app/views/dashboards/show.html.erb
<div class="dashboard3-show">
  <br>
  <h2>Welcome <%= current_user.name %> </h2>
</div>
<br><br><br>

<% if note = current_user.app_messages.current_message  %>
  <div class="container message-box">
    <% note = current_user.app_messages.current_message %>
    <%= note.message %><br>
    <ul>
      <% note.links.each do |title, href| %>
      <li><%= link_to title, href, style: "color:white", target: "_blank" %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="new-entry">
  <%= link_to "New Journal Entry", new_journal_entry_path, class: 'btn btn-default' %>
</div>